### ISSUE TITLE
Use Releases for distributing app packages (.deb/.tar.gz)

### ISSUE THREAD

**Issue by PHLAK** [kasramp/UbuntuIndicatorWeather#1]
I'd like to suggest [tagging versions](https://help.github.com/articles/working-with-tags/) and utilizing the [Releases](https://help.github.com/articles/creating-releases/) feature for distributing your compiled packages (.deb and .tar.gz files).  It's not recommended to put packages in the source code.

**Comment by kasramp** [comment]
@PHLAK great idea I'll use it :+1:
