### ISSUE TITLE
Pluralise "Preference" Menu Option

### ISSUE THREAD

**Issue by d0od88** [kasramp/UbuntuIndicatorWeather#10]
Line 75 of Indicator-Weather.py: 

`self.preference_item = Gtk.MenuItem("Preference")`

should read

`self.preference_item = Gtk.MenuItem("Preferences")`

as there is more than one 'preference'.

**Comment by OSryx** [comment]
but you can fix this an made pull request, don't you ? :+1:

**Comment by kasramp** [comment]
Fixed it.
