### ISSUE TITLE
Location gets displayed as number

### ISSUE THREAD

**Issue by hackel** [kasramp/UbuntuIndicatorWeather#14]
I've just installed indicator-weather 0.6 and it is displaying my location as "3343."  I'm actually in Minneapolis, USA, and I believe it is detecting my location correctly.  ip-api.com is accurate, and the temperature matches what it shows on openweathermap.org.  I entered in my lat/lng manually, and the number changed to 2683.  I'm not sure what this corresponds to.  On openweathermap.org, my city is 5037649.

**Comment by kasramp** [comment]
A similar bug addressed recently (below link), but it's not in the stable release yet. Planned for v0.7. However, if you don't mind can you share the lat and lon that shows number so I can do some testing?
https://github.com/kasramp/UbuntuIndicatorWeather/commit/ea2c3f1cf8b98a7b47e7ecc1de7047b819045290

**Comment by hackel** [comment]
When I turn on auto location, it just shows 0,0 for lat/lon.  If I insert the lat/lng for Minneapolis, USA (44.9706756,-93.3315183), it displays "4043" as the location.

**Comment by hackel** [comment]
I just built the latest code from master, and now the location (using the lat/lon listed above) is displayed as "Wayzata Boulevard".  That is the name of a road, so it seems like a somewhat odd choice.

If I turn on auto-location, it displays the name of the street my flat is on, even though I'm at work now.  Where is it getting this data?  At least I know it's detecting a fairly close location!

**Comment by kasramp** [comment]
There are two webservices are utilized, one is for getting the lat/lon based on your IP address which is `Ip-api.com`. Another one is a customized in-house webservice which is develop on top of two other webservices `http://api.openweathermap.org/` and `http://www.openstreetmap.org` to detect weather temperature and reverse geocoding. At the moment the bottle neck is in `ip-api.com` that sometimes doesn't provide correct lat/lon corresponding to IP address.

**Comment by kasramp** [comment]
By the way keep note that if your location is changed it takes maximum 15 minutes to detect the new location. The reason is that the interval for calling the services is every 15 minutes to avoid exhausting webservices as well as shorten battery life.

**Comment by hackel** [comment]
Thanks, keep up the good work!
