### ISSUE TITLE
Build. Deb package 

### ISSUE THREAD

**Issue by OSryx** [kasramp/UbuntuIndicatorWeather#15]
Following an issue about ppa, i can make a. Deb package for 0.7 UIW

**Comment by Kycko** [comment]
@OSryx seems like @kasramp can make it too, because we see .debs in [Releases] (https://github.com/kasramp/UbuntuIndicatorWeather/releases)

**Comment by OSryx** [comment]
Hhh okey any way if you want i can contribute that @kycko

**Comment by kasramp** [comment]
Thanks @Kycko for your contribution on Debian package standardization. Issue resolved.
