### ISSUE TITLE
PPA install on 16.04 misses 'gi' dependency

### ISSUE THREAD

**Issue by derPuntigamer** [kasramp/UbuntuIndicatorWeather#18]
The application won't start due to the following error:

`Traceback (most recent call last):
  File "/usr/bin/indicator-weather", line 23, in <module>
    import gi
ImportError: No module named gi`

Installing the 'python-gi' solves the problem.

**Comment by derPuntigamer** [comment]
Oh, I see the dependency is already in the DEB control file, please update the PPA.

**Comment by kasramp** [comment]
@derPuntigamer thanks for reporting the issue. The missing dependency's already added. I will update PPA soon.

**Comment by kasramp** [comment]
Resolved
