### ISSUE TITLE
Can't alter any preferences on Ubuntu 16.04(PPA)

### ISSUE THREAD

**Issue by n8willis** [kasramp/UbuntuIndicatorWeather#21]
Attempting to set any of the preferences in 0.8.1 on Ubuntu 16.04 (via the ppa) fails. 

Clicking the "OK" button triggers this error/warning:
`Traceback (most recent call last):
  File "/usr/lib/ubuntu-indicator-weather/preference.py", line 65, in on_ok_button_clicked
    self.configuration.set_auto_start(str(switch_autostart.get_active()).title())
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 176, in set_auto_start
    return self.ini_start_up.set(Startup.SECTION_DESKTOP_ENTRY, Startup.SETTING_NAME_X_GNOME_AUTO_START_ENABLED, value.lower())
AttributeError: 'NoneType' object has no attribute 'set'
`

The Preferences window does not close, nor does the indicator get updated to reflect the requested change(s).

All other packages on this machine are up-to-date, FTR....

**Comment by kasramp** [comment]
@n8willis thanks for reporting the bug, I will look into it.

**Comment by kasramp** [comment]
Fixed in v0.8.2
