### ISSUE TITLE
Python-warnings polluting system logs

### ISSUE THREAD

**Issue by khurshid-alam** [kasramp/UbuntuIndicatorWeather#28]
Can you please fix these warnings?

`/usr/bin/indicator-weather:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.`

It's annoying and polluting my syslog.

**Comment by pywill** [comment]
@khurshid-alam Do you have some capture of that issue in a picture? , maybe i could look it and make something to help you but i need to know what i am doing

**Comment by pywill** [comment]
@khurshid-alam @kasramp 
I have added this line to indicator-weather and it worked for me, try it by yourself:
gi.require_version('AppIndicator3', '0.1') in line 28, after gi.require_version('Gtk', '3.0') in line 27
[indicator-weather.txt](https://github.com/kasramp/UbuntuIndicatorWeather/files/777449/indicator-weather.txt)

**Comment by khurshid-alam** [comment]
Thanks. Yes it works.

**Comment by pywill** [comment]
@khurshid-alam  Ok, i am glad to help you from Cuba!!!!!! LOL!!!!!!!

**Comment by pywill** [comment]
@kasramp Hi, it is not my project but i really think that will be good if you add the line mentioned cause i can´t do it by myself. Thanks

**Comment by kasramp** [comment]
@pywill thanks for helping out for this issue, I have added the code. It's working great.
Thanks @khurshid-alam for reporting it.
