### ISSUE TITLE
Manual location

### ISSUE THREAD

**Issue by psukys** [kasramp/UbuntuIndicatorWeather#3]
It would be nice to be able to set the location manually, as the automatic one is pretty off.

**Comment by kasramp** [comment]
@psukys, ok sure. However, on API side I've applied some enhancements to increase the accuracy of the automatic location detection. I'll be glad if you share your experience after changes in the API. so I can fix it further if still has severe problem.

**Comment by psukys** [comment]
Alright, I'll try the enhancements whenever I'll be at the place with network that showed me the "pretty off" location.

**Comment by kasramp** [comment]
@psukys thanks for your help.

**Comment by psukys** [comment]
Here is an example from my home network, where I am in Munich (blue dot, deduced by google services) and kassel is the red pin, deduced by your program. The distance is around 380 kilometres.
![selection_193](https://cloud.githubusercontent.com/assets/1302529/16720993/2a082e5c-473c-11e6-9da3-38ef1d82a1e9.png)

**Comment by kasramp** [comment]
@psukys thanks for the picture. I'll be investigating the problem and try to fix the accuracy problem. Definitely the location is pretty off.

**Comment by ShinzJr** [comment]
I think it's because the location API uses IP address, which is sometimes not accurate.

**Comment by kasramp** [comment]
Addressed the issue in the release v0.5.
