### ISSUE TITLE
Add weather description for that day (e.g. 'showery')

### ISSUE THREAD

**Issue by kasramp** [kasramp/UbuntuIndicatorWeather#31]

**Comment by pywill** [comment]
@kasramp Hi I have some good ideas for showing the day's description,when you have done with those classifications let me know it and i will start my work.

**Comment by kasramp** [comment]
@pywill - great. I have replaced weather condition with weather description which is much more intuitive. Let me know your idea and how do you want to proceed with it. For that I keep the issue open.

**Comment by pywill** [comment]
@kasramp Hi if you like, you can close this issue , i will work in my idea and make a pull request so you can check it. It´s not too much , just a function that shows an ubuntu notification  every time get_weather is called and tells to users the descritpion of the day and shows its icon.

**Comment by pywill** [comment]
@kasramp Also i have a question, how the program knows wath is the path to the icon in indicator-weather script?

**Comment by kasramp** [comment]
@pywill - ok thanks. Just a side note, it is good to show notification if the weather condition/description has changed. Otherwise, I don't think so displaying weather description would be useful every 15 minutes (every 15 minutes, get_weather method is get called).
The icon path is under `/usr/share/icons/` but the icon is changed based on theme, that's why you do not need to give full path or relative path. Just use icon names that are located under `/usr/share/icons` and the program automatically picks up. 
This is the list of icon names for weather:
`"weather-clear",
"weather-clear-night",
"weather-few-clouds",
"weather-few-clouds-night",
"weather-clouds",
"weather-clouds-night",
"weather-overcast",
"weather-showers",
"weather-showers-scattered",
"weather-storm",
"weather-snow",
"weather-fog"`
