### ISSUE TITLE
Hide location should only hide location in the task bar

### ISSUE THREAD

**Issue by hexion** [kasramp/UbuntuIndicatorWeather#32]
There are two places where one can see the location, the taskbar and the menu on click.
If the option to hide the location is enabled, this is hidden from both places, so the user cannot tell the location unless he goes to options again and disables this option.

In my opinion, the location should never be hidden from the menu, only from the taskbar.

**Comment by kasramp** [comment]
Great catch @hexion. I will fix it, thanks
