### ISSUE TITLE
User can´t set the wind scale

### ISSUE THREAD

**Issue by pywill** [kasramp/UbuntuIndicatorWeather#34]
Lines 169-174 uses a scale for wind but there is not an space in the GUI for user to set the wind scale he wants.Can you write some code to improve configurability of the project?

**Comment by kasramp** [comment]
@pywill - yes we can. I labeled this as enhancement. This is where we can work on it. Either we can change it from the webservice (preferable) or do the unit conversion in the indicator (less preferable). We should try to keep the indicator logic as simple as possible.

**Comment by kasramp** [comment]
@pywill - if you are interested to change the webserivice code, have a look at Eris project: 
https://github.com/kasramp/Eris
It's developed in Java :-)

**Comment by pywill** [comment]
@kasramp jaja i wish to but i only know a bit of python, that is a task for an experienced one like you, however i think we could do the wind unit conversion in the indicator, it is not too difficult and we could do it by adding a combobox in preferences dialog so the user can select a scale, and then we just have to check it and ifn dependency of the selected scale perform a unit conversion or not.
