### ISSUE TITLE
Unable to add a location

### ISSUE THREAD

**Issue by krampstudio** [kasramp/UbuntuIndicatorWeather#44]
Since a recent update, I'm not able to add a location, with the following message : 

```
Unknown error occurred while picking up location data. Please try again later.
```

![add-location-error](http://pix.toile-libre.org/upload/original/1494489545.png)

 - _OS_ : Ubuntu 16.04.2 LTS
 - _package_ : indicator-weather 13.8.0
 - _repo_ : http://ppa.launchpad.net/noobslab/indicators/ubuntu

Thanks for the awesome software !

**Comment by kasramp** [comment]
@krampstudio - the bug you are facing doesn't related to `Simple Weather Indicator`. It relates to `Weather Indicator` app which is maintained by different people in a different repository.  See here:
[https://launchpad.net/weather-indicator](https://launchpad.net/weather-indicator)
The name `indicator-weather` is just coincidental between this app (Simple Weather Indicator) and Weather Indicator. If you check the release page of this repo, you will see we haven't even reached to version 1.0 yet. 
As far as I know `Weather Indicator` is not maintained anymore.
You can give a try to `Simple Weather Indicator` if you like, though is not as feature rich as `Weather Indicator`. For further information about `Simple Weather Indicator`, have a look at below link:
[http://simpleweatherindicator.madadipouya.com/](http://simpleweatherindicator.madadipouya.com/)
