### ISSUE TITLE
Weird 'Autostart' button on elementaryOS

### ISSUE THREAD

**Issue by J0Ar** [kasramp/UbuntuIndicatorWeather#46]
![bildschirmfoto von 2017-10-08 20 51 58](https://user-images.githubusercontent.com/23266409/31319947-92526d74-ac6c-11e7-9749-77fb307c6e29.png)

**Comment by kasramp** [comment]
@J0Ar - fixed the bug. But have not released it yet. To test it out, what you can do is:
`git clone git@github.com:kasramp/UbuntuIndicatorWeather.git`
Then `cd UbuntuIndicatorWeather`
Lastly `sudo ./install.sh`
