### ISSUE TITLE
Use integer values for temperatures

### ISSUE THREAD

**Issue by mabkenar** [kasramp/UbuntuIndicatorWeather#5]
I don't think people really care about sub-integer temperatures. I mean, 17°C and 17.4°C is essentially the same temperature to me. Moreover, reporting temperature of long time periods with 0.1°C accuracy is not scientifically meaningful since the temperature will surely fluctuate during this time and through the region.

Rounding all temperatures to integer values instead removes some clutter from the app, making it more useful when you want to very quickly check the weather.

At the end, this is my personal taste. Feel free to close this issue. Thanks for this beautiful and useful app that you have made.

I filed the same issue with [Forecastie](https://github.com/martykan/forecastie) recently.

**Comment by kasramp** [comment]
@mabkenar I have added a new toggle in preference to round temperature. It's available in v0.6
