### ISSUE TITLE
Freezes when updating

### ISSUE THREAD

**Issue by mrcodedev** [kasramp/UbuntuIndicatorWeather#56]
Hello,

I'm in version 16.04 of Ubuntu and a few days ago I realize that the indicator weather stays frozen, doesnt respond. When I give it to update it is when it stays frozen, it does not allow to do anything else.
I have done some tests, and since it doesnt geolocate me well I put my GPS location. Well, when I dont have the geolocation on, it works (but it does not say exactly where I am), but when I put it manually, it causes it to freeze and not work. I have tried in the previous version to the current one and it works. What can happen?.
Greetings

**Comment by kasramp** [comment]
@mrcodedev can you provide that coordinate you enter manually? 
It might be a bug with the backend service or some corner case that is not handled.

**Comment by mrcodedev** [comment]
Yeah, is this: Latitude 40,253551 and Longitude -3,820637.

**Comment by kasramp** [comment]
![pic](https://user-images.githubusercontent.com/4501120/35023086-1dad4da2-fb74-11e7-8dfb-069fc6e482e5.jpg)
^ @mrcodedev - is Calle del Pais Vasco correct location?

**Comment by mrcodedev** [comment]
Yeah, i put this and show calle pais vasco. Then it isnt updated anymore because it stays frozen and you cant even enter preferences or you can close the application

**Comment by kasramp** [comment]
@mrcodedev - Correct, the app freezes afterward. Let me dig in further.

**Comment by mrcodedev** [comment]
Thank you kasramp!!!

**Comment by mrcodedev** [comment]
Is there any news?

**Comment by kasramp** [comment]
@mrcodedev - fixed the bug. But have not released it yet. To test it out, what you can do is:
`git clone git@github.com:kasramp/UbuntuIndicatorWeather.git`
Then `cd UbuntuIndicatorWeather`
Lastly `sudo ./install.sh`

**Comment by mrcodedev** [comment]
It works well!!!. Thank you very much for everything and for your great work.
