### ISSUE TITLE
Option to hide location name on the panel

### ISSUE THREAD

**Issue by khurshid-alam** [kasramp/UbuntuIndicatorWeather#6]
For some locations , the name could be very long, thus occupying a vast horizontal space on the panel. 

It would be nice if we can **hide/toggle** location name on the panel from the preference.

![indicator-weather](http://i.imgur.com/DRnYGEL.png)

**Comment by khurshid-alam** [comment]
@kasramp Anything on this?

**Comment by kasramp** [comment]
@khurshid-alam addressed the issue in v0.6

**Comment by khurshid-alam** [comment]
Wow! Thanks.
