### ISSUE TITLE
Create a PPA for easy installation and update

### ISSUE THREAD

**Issue by khurshid-alam** [kasramp/UbuntuIndicatorWeather#9]
PPA for easy installation and update.

Thanks

**Comment by Kycko** [comment]
**kasramp**, I can upload a package into my PPA if you want, or give you some links about creating your own PPA ^_^

**Comment by kasramp** [comment]
@Kycko I would be awesome if you can provide some links on creating PPA. Thanks :-)

**Comment by Kycko** [comment]
The main document is a [launcpad help pages] (https://help.launchpad.net/Packaging/PPA?action=show&redirect=PPA). You will need to follow many links to finally get things done :)
I haven't find another good **english** guides, only **ru** one.

And if you want to know how **correctly build .deb package with following to all Debian standarts**, there is a great [Debian New Maintainers' Guide] (https://www.debian.org/doc/manuals/maint-guide/index.en.html)

**Comment by OSryx** [comment]
I can take care of the deb package. I launched an issue for that please assign it to me

**Comment by kasramp** [comment]
Thanks a lot @Kycko.
In regards of deb package @OSryx, at the moment we have it (in releases) but not sure how standard it's. Need to go though the guideline and apply any adjustment if necessary.

**Comment by Kycko** [comment]
I'll make some commits in debian/ folder, especially changelog must be splitted into two parts: *program changelog* must be placed in /, and *package changelog* must be in debian/, but it must contain only changes for package, not for program

**Comment by kasramp** [comment]
@Kycko  when I try to build the package in Launchpad I get this error:
`dpkg-buildpackage: source package indicator-weather
dpkg-buildpackage: source version 0.7ubuntu
dpkg-buildpackage: source distribution trusty
 dpkg-source --before-build indicator-weather-0.7ubuntu
dpkg-buildpackage: host architecture i386
 fakeroot debian/rules clean
dh clean --with python2
dh: unable to load addon python2: Can't locate Debian/Debhelper/Sequence/python2.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python2 module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at (eval 3) line 2.
BEGIN failed--compilation aborted at (eval 3) line 2.

make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2`
Do you have any idea how to fix it? I'm literally clueless :-(

**Comment by Kycko** [comment]
@kasramp, what do you mean in **build the package in Launchpad**?
You must build it on your local machine, and then just send **source.changes** to Launchpad. Note that you **must** have a GPG-signature associated with your Launcpad-account, and you must build a package with `debuild` command, without `-us -uc` options. These options are creating a package without your signature, so don't use them.

**Comment by khurshid-alam** [comment]
@kasramp @Kycko Actually launchpad can compile source on the fly through launchpad recipes. Of course it is recommended to compile locally first so that it won't abuse launchpad build system. The initial setup is lengthy, but once done, it will compile whenever it detects any changes. The workflow is something like this:

1. Create a project under launchpad (Ubuntu-Indicator-Weather) if it hasn't been done already.

2. Create a team : Ubuntu-Indicator-Weather-Maintainer

3. Use launcpad importer to import source from github on behalf of above team. Don't use special character on commit message. It will create a branch; ie `lp:ubuntu-indicator-weather`

4. Create a PPA.

4. Create a recipe for the source code of `lp:ubuntu-indicator-weather` & choose above PPA to upload

5. That's all. 

I am trying to do the same in my own ppa, just to check whether it compiles or not. I wiil reply once done.

**Comment by khurshid-alam** [comment]
Nah, it won't work as you already used gpg signature on commit messages (15293c9b0b924129bbdb42b50ce0a08c7e3803fb) . Launchpad import doesn't allow that. If you remove that from commit and then re-apply (basically rewriting git history), then only it can work.

As of now, manually uploading source.changes is the only way as @Kycko mentioned.

**Comment by Kycko** [comment]
@khurshid-alam only Kasramp can write to this repo, so please try to use [my one] (https://github.com/Kycko/UbuntuIndicatorWeather). It doesn't contain latest commits, but I've re-committed debian directory without signature

**Comment by kasramp** [comment]
@Kycko @khurshid-alam thanks for all your help, the problem was due to the missing dependencies in `control` file. Signature and everything else has setup and finally managed to create PPA and build successfully. I've updated Readme file and put the PPA link with description.

**Comment by Kycko** [comment]
@kasramp excellent! Now we must not remember to manually update this app every time it is updated ^_^

**Comment by Kycko** [comment]
[Only one day after PPA creating] (http://www.omgubuntu.co.uk/2016/09/simple-weather-indicator-ppa-app-icon?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+%28OMG%21+Ubuntu%21%29)

**Comment by kasramp** [comment]
Thank you so much for all your efforts @Kycko,  without your help creating PPA wouldn't be possible.
